[package]
name = "lab01"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.1"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "sort_benchmark"
harness = false
